destroy

diff --git a/.github/workflows/terraform.yml b/.github/workflows/terraform.yml
--- a/.github/workflows/terraform.yml
+++ b/.github/workflows/terraform.yml
@@ -38,27 +38,32 @@ jobs:
           id: init
           run: terraform init -backend-config "bucket=$BUCKET_TF_STATE"
 
-        - name: Terraform Format
-          id: fmt
-          run: terraform fmt -check
-          continue-on-error: true 
 
-        - name: Terraform Validate
-          id: validate
-          run: terraform validate
 
-        - name: Terraform Plan
-          id: plan
-          run: terraform plan -no-color -input=false -out planfile
-          continue-on-error: true 
+        # - name: Terraform Format
+        #   id: fmt
+        #   run: terraform fmt -check
+        #   continue-on-error: true 
 
-        - name: Terraform Plan Status 
-          if: steps.plan.outcome == 'failure'
-          run: exit 1
+        # - name: Terraform Validate
+        #   id: validate
+        #   run: terraform validate
 
-        - name: Terraform Apply
-          id: apply
-          if: github.ref == 'refs/heads/main' && github.event_name == 'push'
-          run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+        # - name: Terraform Plan
+        #   id: plan
+        #   run: terraform plan -no-color -input=false -out planfile
+        #   continue-on-error: true 
 
+        # - name: Terraform Plan Status 
+        #   if: steps.plan.outcome == 'failure'
+        #   run: exit 1
+
+        # - name: Terraform Apply
+        #   id: apply
+        #   if: github.ref == 'refs/heads/main' && github.event_name == 'push'
+        #   run: terraform apply -auto-approve -input=false -parallelism=1 planfile
+
+        - name: Terraform Destroy
+          id: destroy
+          run: terraform destroy -auto-approve
 
